config/routes.rb
CodeCache::Application.routes.draw do
  get '/', to: redirect('/snippets')

  get '/search' => 'snippets#search', :as => :search, :defaults => {:format => 'json' }
  scope '/s' do
    get '/' => 'snippets#index', :as => :snippets
    get '/:uuid' => 'snippets#edit', :as => :snippet
    post '/:uuid' => 'snippets#update', :as => :edit_snippet, :defaults => { :format => 'json' }
    post '/' => 'snippets#create', :as => :new_snippet, :defaults => { :format => 'json' }
  end
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  include Elasticsearch::Model
  #before_save :set_uuid

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :title, analyzer: 'english', index_options: 'offsets'
      indexes :uuid, analyzer: 'english', index_options: 'offsets'
    end
  end

  def initialize(attributes = {})
    super
    unless self.uuid?
      logger.debug "GENERATE UUID"
      self.uuid = SecureRandom.uuid.gsub('-', '')[0..8]
    end
  end

  def to_param
    uuid
  end
 
  #def set_uuid
  #  unless self.uuid?
  #    logger.debug "Setting Uuid"
  #    #self.uuid = SecureRandom.uuid.gsub('-', '')[0..8]
  #  end
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :set_snippet, only: [:index, :edit, :update, :destroy]

  def search
    @snippets = Snippet.search params[:q], default_operator: 'AND'
    print @snippets.results.first
    #response = Article.search query:     { match:  { title: "Fox Dogs" } },
    #                      highlight: { fields: { title: {} } }
    #respond_to do |format|
    #    format.json { render json: @snippets }
    #end
  end

  # GET /snippets
  # GET /snippets.json
  def index
    @snippet = Snippet.new
    logger.debug @snippet
    logger.debug "New snippet id: #{@snippet.uuid}"
  end

  # GET /snippets/1/edit
  def edit
    render :index
  end

  # POST /snippets
  # POST /snippets.json
  def create
    logger.debug "CREATE"
    @snippet = Snippet.new(snippet_params)

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        #format.json { render action: 'show', status: :created, location: @snippet }
        format.json { render json: @snippet }
      else
        #format.html { render action: 'new' }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippets/1
  # PATCH/PUT /snippets/1.json
  def update
    logger.debug "UPDATE"
    respond_to do |format|
      if @snippet.update(snippet_params)
        #format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { head :no_content }
      else
        #format.html { render action: 'edit' }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to snippets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snippet
      @snippet = Snippet.where(uuid: params[:uuid]).first
      @snippets = Snippet.all.order('created_at desc').limit(5)
      logger.debug @snippet
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snippet_params
      params.require(:snippet).permit(:content, :language, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeCache</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<style type="text/css" media="screen">
    #editor { 
        width:100%;
        height:100px;
    }

    html, body {
    height: 100%;
    margin: 0px;
    padding: 0px;
}

#wrapper {
    height: 100%;
    margin: auto;
    position: relative;
}

#header {
    height: 40px;
}

#content {
    position:absolute;
    bottom:0px;
    top: 40px;
    width:100%;
    overflow: auto;
}
#snippet_title, #snippet_language, #search_query{
    font-size:18px;
    line-height:24px;
    border:0;
}
#search_results{
    position:absolute;
    z-index:1000;
    list-style:none;
    background:#efefef;
    width:100%;
    margin:0;
    padding:0;
    border-bottom:2px solid #ccc;
    display:none;
}
#search_results li{
    margin:0;
    padding-left:15px;
}
#search_container{
position:relative;
}

</style>
</head>
<body data-no-turbolink>

<div id="wrapper">
<%= yield %>
</div>

<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<script src="//cdnjs.cloudflare.com/ajax/libs/ace/1.1.3/ace.js"></script>
<script>
    $(function(){
        var editor = ace.edit("editor");
        var language = $('#snippet_language').val();
        var save_timer, search_timer;

        //editor.setTheme("ace/theme/monokai");
        if (language){
            editor.getSession().setMode("ace/mode/" + language); 
        }
        editor.getSession().on('change', function(e) {
            $('#snippet_content').val(editor.getValue());
            clearTimeout(save_timer);
            save_timer = setTimeout(function(){
                save();
            }, 500);
        });

        function resizeAce(){
            $('#editor').height($('#content').height() - 40);
        }
        $( window ).resize(function() {
            resizeAce()
        });
        resizeAce()

        function save(){
            var url = $('#snippet_form').attr('action');
            $.post(url, $( "#snippet_form" ).serialize(), function(data){
                console.log("Saved");
                console.log(data);
                if (url === "/s" || url === "/s/"){
                    var newUrl = "/s/" + data['uuid'];
                    $('#snippet_form').attr('action', newUrl);
                    if (history && history.pushState) { 
                        history.replaceState(null, document.title, newUrl);
                    }
                }
            });
        }

        function search(){
            var $search_results = $('#search_results');
            $search_results.empty();
            var url = '/search?q=' + $('#search_query').val();
            $.get(url, function(data){
                var snippets = data.snippets;
                if (snippets){
                    $search_results.show();
                    $.each(snippets, function(n, snippet){
                        $search_results.append('<li><a href="/s/' + snippet.uuid + '">' + snippet.title + '</a>');
                    });
                    console.log(data);
                }
            });
        }

        $('#search_query').on('keyup', function(e){
            clearTimeout(search_timer);
            search_timer = setTimeout(function(){
                search();
            }, 300);
        });
    });
</script>
</body>
</html>

app/views/snippets/_form.html.erb
<%= form_for @snippet, :method => "post", :html => { :id => 'snippet_form' }  do |f| %>
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div style="height:40px;">
    <%= link_to 'New', snippets_path %>
    <%= f.text_field :title, :placeholder => "snippet title" %>
    <%= f.text_field :language%>
</div>
  <div id="editor"><%= @snippet.content %></div>
    <!--<%= f.submit %>-->
    <%= f.hidden_field :content %>
<% end %>

app/views/snippets/edit.html.erb
<%= render 'form' %>

<%= link_to 'Home', snippets_path %>

app/views/snippets/index.html.erb
<div id="header">
    <div id="search_container">
        <input type="text" name="search" id="search_query">
        <ul id="search_results"></ul> 
    </div>
    <ul style="display:none;">
        <% @snippets.each do |snippet| %>
        <li>
            <%= snippet.content %>
            <br><%= snippet.language %>
            <br><%= link_to snippet.uuid, snippet %>
        </li>
        <% end %>
    </ul>
</div>
<div id="content">
    <%= render 'form' %>
</div>

app/views/snippets/new.html.erb
<h1>New snippet</h1>

<%= render 'form' %>

<%= link_to 'Back', snippets_path %>

app/views/snippets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @snippet.content %>
</p>

<p>
  <strong>Type:</strong>
  <%= @snippet.type %>
</p>

<%= link_to 'Edit', edit_snippet_path(@snippet) %> |
<%= link_to 'Back', snippets_path %>